name: iOS CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
#     - name: set up JDK 1.8
#       uses: actions/setup-java@v1
#       with:
#         java-version: 1.8
    - name: Check versions
      run: |
        node -v
        npm -v
        xcodebuild -version
        java -version
        docker -v
#     - name: Build
#       run: |
#         npm install -g cordova
#         cd hello
#         npm install
#         cordova build ios
#     - uses: actions/upload-artifact@master
#       with:
#         name: ios-app
#         path: hello/platforms/ios/build/emulator/HelloWorld.app
