name: iOS CI

on: [push]

jobs:
  build-assets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check versions
      run: |
        docker -v
        docker-compose --version

  build-app:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    # - name: Install Dependencies
    #   run: |
    #     brew -v
    #     brew cask install docker
    #     docker-compose --version
    #     docker -v
    - name: Check versions
      run: |
        node -v
        npm -v
        xcodebuild -version
        java -version
