name: iOS CI

on: [push]

jobs:
  build-assets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check versions
      run: |
        docker -v
        docker-compose --version
    - name: Create test dist
      run: |
        mkdir tmp
        echo "Writing temp file..."
        echo "Hello, world!" > ./tmp/dist.txt
  build-app:
    needs: build-assets
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    # - name: Install Dependencies
    #   run: |
    #     brew -v
    #     brew cask install docker
    #     docker-compose --version
    #     docker -v
    - name: Check versions
      run: |
        node -v
        npm -v
        xcodebuild -version
        java -version
    - name: Check dist
      run: |
        ls -l
        ls -l tmp
        cat ./tmp/dist.txt
